version: "3"

services:
  moynihan:
    image: moynihan/moynihan.io:latest
    restart: unless-stopped

  traefik:
    container_name: traefik
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker --certificatesresolvers.letsencrypt.acme.email=encrypt@moynihan.io --certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web --entryPoints.web.address=:80 --entryPoints.web-secure.address=:443
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shadow:/shadow:ro
      - ./traefik:/traefik
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik-netsoc.moynihan.io`)"
      traefik.http.routers.traefik.entrypoints: "web-secure"
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik.service: "traefik-service"
      traefik.docker.network: "traefik"
      traefik.http.middlewares.traefik-auth.basicauth.usersfile: "/shadow"
      traefik.http.routers.traefik.middlewares: "traefik-auth@docker"
