version: "3"

services:
  moynihan:
    container_name: "moynihan"
    image: moynihan/moynihan.io:latest
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.moynihan.rule: "Host(`moynihan.io`)"
      traefik.http.routers.moynihan.entrypoints: "web"
      traefik.http.services.moynihan-service.loadbalancer.server.port: "80"
      traefik.http.routers.moynihan.service: "moynihan-service"
      traefik.docker.network: "traefik"
  
  

  traefik:
    container_name: traefik
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shadow:/shadow:ro
      - ./traefik:/traefik
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik-netsoc.moynihan.io`)"
      traefik.http.routers.traefik.entrypoints: "web"
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik.service: "traefik-service"
      traefik.docker.network: "traefik"
      traefik.http.middlewares.traefik-auth.basicauth.usersfile: "/shadow"
      traefik.http.routers.traefik.middlewares: "traefik-auth@docker"
